# Generated by Django 4.2.8 on 2024-02-02 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appliances",
            name="description",
        ),
    ]
